par.name = c(expression(tilde(mu)[1]), expression(tilde(mu)[2]), expression(tilde(mu)[3]),
expression(tilde(sigma)[11]), expression(tilde(sigma)[21]), expression(tilde(sigma)[22]),
expression(tilde(sigma)[31]), expression(tilde(sigma)[32]), expression(tilde(sigma)[33]))
load(paste(WD.PATH, 'data/mMNI.RData', sep=''))

n = c(10, 50, 100, seq(0, 10000, 200)[-1], seq(10000, 25000, 500)[-1], 
    seq(25000, 40000, 1000)[-1], seq(40000, 50000, 2500)[-1], 
    seq(50000, 100000, 5000)[-1])

### right ###
WD.PATH1 = paste(WD.PATH, 'results/right/', sep='')
SM.mTMVT = read.table(paste(WD.PATH1, 'mTMVT.txt',sep=""))
SM.mTMSL = read.table(paste(WD.PATH1, 'mTMSL.txt',sep=""))
SM.mTMCN = read.table(paste(WD.PATH1, 'mTMCN.txt',sep=""))
SM.mTMVG = read.table(paste(WD.PATH1, 'mTMVG.txt',sep=""))
SM.mTMDE = read.table(paste(WD.PATH1, 'mTMDE.txt',sep=""))
 
# trace plots for the first moments (mean vector)
#win.graph(width=20, height=25)
postscript(paste(WD.PATH1, 'figS1.eps', sep=''), width=7, height=25)
Xlab = seq(0,1e5, length=5)/1e4
par(mfcol=c(5,4), mar=c(4,0,0,0))
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(a) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MVT', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(b) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MSL', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(c) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MCN', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(d) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MVG', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(e) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MDE', 1, line=-3, cex=1, font=2)
par(mar=c(4,2.5,2,0.5))
for(i in 1:2){
  plot(n, SM.mTMVT[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVT1[i], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMSL[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMSL1[i], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMCN[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMCN1[i], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMVG[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVG1[i], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMDE[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMDE1[i], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
}
  plot(n, SM.mTMVT[,3], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[3], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVT1[3], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMSL[,3], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[3], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMSL1[3], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMCN[,3], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[3], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMCN1[3], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMVG[,3], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[3], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVG1[3], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMDE[,3], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[3], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMDE1[3], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
dev.off()

# trace plots for the second moments (variance-covariance matrix)
#win.graph(width=38, height=25)
postscript(paste(WD.PATH1, 'figS2.eps', sep=''), width=32, height=25)
Xlab = seq(0,1e5, length=5)/1e4
par(mfcol=c(5,7), mar=c(4,0,0,0))
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(a) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MVT', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(b) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MSL', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(c) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MCN', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(d) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MVG', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(e) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MDE', 1, line=-3, cex=1, font=2)
par(mar=c(4,2,2,0.5))
for(i in 4:9){
  plot(n, SM.mTMVT[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVT1[i], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMSL[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMSL1[i], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMCN[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMCN1[i], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMVG[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVG1[i], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMDE[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMDE1[i], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
}
dev.off()

### left ###
WD.PATH2 = paste(WD.PATH, 'results/left/', sep='')
SM.mTMVT = read.table(paste(WD.PATH2, 'mTMVT.txt',sep=""))
SM.mTMSL = read.table(paste(WD.PATH2, 'mTMSL.txt',sep=""))
SM.mTMCN = read.table(paste(WD.PATH2, 'mTMCN.txt',sep=""))
SM.mTMVG = read.table(paste(WD.PATH2, 'mTMVG.txt',sep=""))
SM.mTMDE = read.table(paste(WD.PATH2, 'mTMDE.txt',sep=""))

# trace plots for the first moments (mean vector)
#win.graph(width=20, height=25)
postscript(paste(WD.PATH2, 'figS3.eps', sep=''), width=7, height=25)
Xlab = seq(0,1e5, length=5)/1e4
par(mfcol=c(5,4), mar=c(4,0,0,0))
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(a) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MVT', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(b) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MSL', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(c) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MCN', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(d) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MVG', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(e) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MDE', 1, line=-3, cex=1, font=2)
par(mar=c(4,2.5,2,0.5))
for(i in 1:2){
  plot(n, SM.mTMVT[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVT2[i], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMSL[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMSL2[i], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMCN[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMCN2[i], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMVG[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVG2[i], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMDE[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMDE2[i], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
}
  plot(n, SM.mTMVT[,3], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[3], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVT2[3], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMSL[,3], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[3], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMSL2[3], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMCN[,3], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[3], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMCN2[3], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMVG[,3], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[3], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVG2[3], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMDE[,3], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[3], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMDE2[3], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
dev.off()

# trace plots for the second moments (variance-covariance matrix)
#win.graph(width=38, height=25)
postscript(paste(WD.PATH2, 'figS4.eps', sep=''), width=32, height=25)
Xlab = seq(0,1e5, length=5)/1e4
par(mfcol=c(5,7), mar=c(4,0,0,0))
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(a) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MVT', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(b) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MSL', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(c) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MCN', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(d) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MVG', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(e) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MDE', 1, line=-3, cex=1, font=2)
par(mar=c(4,2,2,0.5))
for(i in 4:9){
  plot(n, SM.mTMVT[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVT2[i], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMSL[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMSL2[i], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMCN[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMCN2[i], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMVG[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVG2[i], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMDE[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMDE2[i], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
}
dev.off()

### doubly ###
WD.PATH3 = paste(WD.PATH, 'results/doubly/', sep='')
SM.mTMVT = read.table(paste(WD.PATH3, 'mTMVT.txt',sep=""))
SM.mTMSL = read.table(paste(WD.PATH3, 'mTMSL.txt',sep=""))
SM.mTMCN = read.table(paste(WD.PATH3, 'mTMCN.txt',sep=""))
SM.mTMVG = read.table(paste(WD.PATH3, 'mTMVG.txt',sep=""))
SM.mTMDE = read.table(paste(WD.PATH3, 'mTMDE.txt',sep=""))

# trace plots for the first moments (mean vector)
#win.graph(width=20, height=25)
postscript(paste(WD.PATH3, 'fig3.eps', sep=''), width=7, height=25)
Xlab = seq(0,1e5, length=5)/1e4
par(mfcol=c(5,4), mar=c(4,0,0,0))
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(a) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MVT', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(b) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MSL', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(c) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MCN', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(d) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MVG', 1, line=-3, cex=1, font=2)
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(e) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MDE', 1, line=-3, cex=1, font=2)
par(mar=c(4,2.5,2,0.5))
  plot(n, SM.mTMVT[,1], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[1], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVT3[1], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMSL[,1], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[1], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMSL3[1], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMCN[,1], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[1], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMCN3[1], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMVG[,1], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[1], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVG3[1], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMDE[,1], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[1], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMDE3[1], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMVT[,2], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[2], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVT3[2], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMSL[,2], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[2], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMSL3[2], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMCN[,2], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[2], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMCN3[2], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMVG[,2], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[2], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVG3[2], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMDE[,2], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[2], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMDE3[2], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMVT[,3], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[3], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVT3[3], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMSL[,3], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[3], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMSL3[3], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMCN[,3], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[3], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMCN3[3], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMVG[,3], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[3], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVG3[3], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMDE[,3], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[3], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMDE3[3], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
dev.off()

# trace plots for the second moments (variance-covariance matrix)
#win.graph(width=38, height=25)
postscript(paste(WD.PATH3, 'fig4.eps', sep=''), width=32, height=25)
Xlab = seq(0,1e5, length=5)/1e4
par(mfrow=c(5,7), mar=c(4,0,0,0))
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(a) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MVT', 1, line=-3, cex=1, font=2)
par(mar=c(4,3,2,0.5))
  plot(n, SM.mTMVT[,4], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[4], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVT3[4], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
for(i in 5:8){
  plot(n, SM.mTMVT[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVT3[i], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
}
  plot(n, SM.mTMVT[,9], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[9], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVT3[9], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')

par(mar=c(4,0,0,0))
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(b) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MSL', 1, line=-3, cex=1, font=2)
par(mar=c(4,3,2,0.5))
for(i in 4:5){
  plot(n, SM.mTMSL[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMSL3[i], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
}
  plot(n, SM.mTMSL[,6], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[6], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMSL3[6], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMSL[,7], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[7], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMSL3[7], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMSL[,8], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[8], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMSL3[8], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
  plot(n, SM.mTMSL[,9], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[9], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMSL3[9], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')


par(mar=c(4,0,0,0))
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(c) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MCN', 1, line=-3, cex=1, font=2)
par(mar=c(4,3,2,0.5))
for(i in 4:5){
  plot(n, SM.mTMCN[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMCN3[i], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
}
  plot(n, SM.mTMCN[,6], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[6], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMCN3[6], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
for(i in 7:9){
  plot(n, SM.mTMCN[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMCN3[i], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
}

par(mar=c(4,0,0,0))
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(d) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MVG', 1, line=-3, cex=1, font=2)
par(mar=c(4,3,2,0.5))
for(i in 4:6){
  plot(n, SM.mTMVG[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVG3[i], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
}
  plot(n, SM.mTMVG[,7], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[7], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVG3[7], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
for(i in 8:9){
  plot(n, SM.mTMVG[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMVG3[i], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
}

par(mar=c(4,0,0,0))
plot(c(0, 1), c(0, 3), type='n', xaxt='n', yaxt='n', xlab='', ylab='', bty='n')
mtext('(e) Truncated', 1, line=-5, cex=1, font=2)
mtext('    MDE', 1, line=-3, cex=1, font=2)
par(mar=c(4,3,2,0.5))
for(i in 4:6){
  plot(n, SM.mTMDE[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMDE3[i], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
}
  plot(n, SM.mTMDE[,7], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[7], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMDE3[7], lty=2, col=2, lwd=1.5)
  legend("topright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
for(i in 8:9){
  plot(n, SM.mTMDE[,i], type='l', lty=1, col=4, xaxt='n', xlab=expression(paste('sample size (', 10^4, ')')), ylab='', main=par.name[i], cex.lab=0.9, las=1)
  axis(1, seq(0,1e5, length=5), labels=Xlab)
  abline(h=par.TMDE3[i], lty=2, col=2, lwd=1.5)
  legend("bottomright", c('empirical','theoretical'), col=c(4,2), lty=c(1,2), cex=0.75, bty='n')
}
dev.off()
